// frontend/react/src/footer/footer.component.tsx
import React from 'react';
import './footer.component.scss';

export default class FooterComponent extends React.Component {

	render() {
		return (
			<footer className="footer">
				<address>
					©Copyright <a href="//egofoxlab.com" target="_blank">EGOFOXLAB</a>
				</address>
			</footer>
		);
	}

}

// frontend/angular/src/app/footer/footer.component.ts
/*
 * Developed by EGOFOXLAB.
 * Site http://egofoxlab.com/
 * Copyright (c) 2019.
 */

import {Component} from "@angular/core";

@Component({
	selector: 'app-footer',
	templateUrl: './footer.component.html',
	styleUrls: ['./footer.component.scss']
})
export class FooterComponent {

}

<footer class="footer">
	<address>
		©Copyright <a href="//egofoxlab.com">EGOFOXLAB</a>
	</address>
</footer>
