// frontend/angular/src/app/header/header.component.ts
/*
 * Developed by EGOFOXLAB.
 * Site http://egofoxlab.com/
 * Copyright (c) 2019.
 */

import {Component} from "@angular/core";

@Component({
	selector: 'app-header',
	templateUrl: './header.component.html',
	styleUrls: ['./header.component.scss']
})
export class HeaderComponent {

}

<header class="header">
	<div class="logo">
		<img src="/assets/images/fox-brand.png" alt="fox-brand.png">

		<span>
			EGO CHAT
		</span>
	</div>
	<div class="chat-name">
		
	</div>
</header>

// frontend/react/src/header/header.component.tsx
import React from 'react';
import './header.component.scss';
export default class HeaderComponent extends React.Component {

	render() {
		return (
			<header className="header">
				<div className="logo">
					<div className="image">
						<div
							style={{backgroundImage: 'url(/assets/images/fox-brand.png)'}}
						/>
					</div>

					<span>
						EGO CHAT
					</span>
				</div>
				<div className="chat-name">

				</div>
			</header>
		);
	}

}
